model_name: 'TemporalCategoricalAE'
loss:
  name: 'category'

optimizer:
  name: 'adam'
  lr: 0.0001
  lookahead:
    k: 5
    alpha: 0.5

general:
  seed: 42
  compile_model: False

  num_epochs: 50
  eval_freq: 50
  keys: ['Total_Loss']